services:
  db:
    image: postgres:17.5
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python ./lami/manage.py runserver 0.0.0.0:8000
    depends_on:
     - db
    volumes: 
      - ./src:/app
    ports: 
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  postgres_data: